export const INDIA_STATES = [
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const STATE_EMOJIS: Record<string, string> = {
  "Delhi": "🏙️",
  "Maharashtra": "🦁",
  "Uttar Pradesh": "⚔️",
  "Tamil Nadu": "🌊",
  "Karnataka": "🌺",
  "Gujarat": "💎",
  "Rajasthan": "🏰",
  "West Bengal": "🐯",
  "Bihar": "🏛️",
  "Punjab": "🌾",
  "Haryana": "⚡",
  "Andhra Pradesh": "🎭",
  "Telangana": "🔱",
  "Kerala": "🌴",
  "Jharkhand": "⛰️",
  "Odisha": "🌸",
  "Assam": "🍵",
  "Madhya Pradesh": "🐆",
  "Chhattisgarh": "🌿",
  "Uttarakhand": "🏔️",
  "Himachal Pradesh": "❄️",
  "Jammu & Kashmir": "🌨️",
  "Goa": "🌅",
  "Manipur": "🎿",
  "Meghalaya": "🌧️",
  "Arunachal Pradesh": "🦅",
  "Nagaland": "🎵",
  "Tripura": "🌳",
  "Mizoram": "🌄",
  "Sikkim": "🏔️",
};
